config/routes.rb
Rails.application.routes.draw do
  root 'pages#landing'
  get 'pages/about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaphoto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<div class="container-fluid container-background">
		<div class="container">


			<ul class="nav nav-inline">
			  <li class="nav-item">
			    <%= link_to "Instaphoto", root_path, class:'nav-landing' %>
			  </li>
			  <li class="nav-item">
			    <%= link_to "О проекте", pages_about_path, class:'nav-landing' %>
			  </li>

			</ul>


    <%= yield %>
		
		</div>
	</div>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
  <h1 class="display-3">О проекте</h1>
  <p class="lead">Instaphoto - это социальная сеть для обмена фотографиями.</p>


  </p>
</div>

app/views/pages/landing.html.erb
<div class="jumbotron jumbotron-landing">
  <h1 class="display-3">Делитесь своими эмоциями</h1>
  <p class="lead">Размещайте свои фотографии и подписывайтесь на публикации ваших друзей.</p>
  <hr class="m-y-2">
  <p class="lead">
    <a class="btn btn-warning" href="#" role="button">Создать аккаунт</a>
    <a class="btn btn-primary" href="#" role="button">Войти</a>
  </p>
</div>